### ISSUE TITLE
在预训练阶段中评估测试集的时候出现以下错误，请问是什么原因？谢谢

### ISSUE THREAD

**Issue by MINGC0816** [jdfxzzy/PEAN#11]
(pean) root@c5682d3d34d0:~/PEAN-main# python main.py --batch_size="1" --mask --rec="aster" --srb="1" --pre_training
loading pretrained parseq model from ./rec_pth/parseq.pt
loading TPEM from TPEM_final.pth
==============================================================================================================
[2024-12-10 14:27:48] | Epoch: [0][80 / 17367] | Loss: 50.119564056396484 | Duration: 18.502737045288086s
--------------------------------------------------------------------------------------------------------------
[2024-12-10 14:28:05] | Epoch: [0][160 / 17367] | Loss: 52.71257781982422 | Duration: 17.228423833847046s
--------------------------------------------------------------------------------------------------------------
[2024-12-10 14:28:22] | Epoch: [0][240 / 17367] | Loss: 50.668731689453125 | Duration: 16.633453369140625s
--------------------------------------------------------------------------------------------------------------
[2024-12-10 14:28:38] | Epoch: [0][320 / 17367] | Loss: 55.8146858215332 | Duration: 16.297353982925415s
--------------------------------------------------------------------------------------------------------------
==============================================================================================================
evaling ./textzoom/test/easy
loading pretrained aster model from ./rec_pth/aster_demo.pth.tar
loading pretrained crnn model from ./rec_pth/crnn.pth
loading pre-trained moran model from ./rec_pth/moran_demo.pth
Traceback (most recent call last):
  File "/root/PEAN-main/main.py", line 60, in <module>
    main(config, args)
  File "/root/PEAN-main/main.py", line 26, in main
    Mission.train()
  File "/root/PEAN-main/interfaces/super_resolution.py", line 141, in train
    metrics_dict = self.eval(model, val_loader, epoch, parseq)
  File "/root/PEAN-main/interfaces/super_resolution.py", line 273, in eval
    images_hr, images_lr, label_strs, _ = data
ValueError: not enough values to unpack (expected 4, got 1)

**Comment by jdfxzzy** [comment]
我这边是没有问题的，因此仅凭您提供的信息无法判断是什么问题。您可以自行通过debug调试解决。

**Comment by 761qgmpgz943** [comment]
仓库代码本来就是有问题的，改了两次还是错的

**Comment by 761qgmpgz943** [comment]
请问作者到底跑了仓库的代码了吗，明确有问题

**Comment by xiehuilong** [comment]
可能需要修改一下get_val_data：
    def get_val_data(self):
        cfg = self.config.TRAIN
        assert isinstance(cfg.VAL.val_data_dir, list)
        dataset_list = []
        loader_list = []
        for data_dir_ in cfg.VAL.val_data_dir:
            val_dataset, val_loader = self.get_test_data(data_dir_)
            dataset_list.append(val_dataset)
            loader_list.append(val_loader)
        return dataset_list, loader_list

**Comment by MINGC0816** [comment]
> 可能需要修改一下get_val_data： def get_val_data（self）： cfg = self.config.TRAIN assert isinstance（cfg.VAL.val_data_dir， list） dataset_list = [] loader_list = [] 用于 cfg 中的 data_dir_。VAL.val_data_dir： val_dataset， val_loader = self.get_test_data（data_dir_） dataset_list.append（val_dataset） loader_list.append（val_loader） 返回 dataset_list， loader_list

你好，你修改完运行成功了吗，我修改了之后遇到新问题：
==============================================================================================================
[2025-01-04 19:29:18] | Epoch: [0][80 / 2170] | Loss: 46.094844818115234 | Duration: 32.070534229278564s
--------------------------------------------------------------------------------------------------------------
[2025-01-04 19:29:50] | Epoch: [0][160 / 2170] | Loss: 37.31065368652344 | Duration: 32.277491331100464s
--------------------------------------------------------------------------------------------------------------
[2025-01-04 19:30:22] | Epoch: [0][240 / 2170] | Loss: 40.38260269165039 | Duration: 31.45424509048462s
--------------------------------------------------------------------------------------------------------------
[2025-01-04 19:30:54] | Epoch: [0][320 / 2170] | Loss: 36.98100280761719 | Duration: 31.452784538269043s
--------------------------------------------------------------------------------------------------------------
==============================================================================================================
evaling ./textzoom/test/easy
loading pretrained aster model from ./rec_pth/aster_demo.pth.tar
loading pretrained crnn model from ./rec_pth/crnn.pth
loading pre-trained moran model from ./rec_pth/moran_demo.pth
[2025-01-04 19:36:48] | PSNR 15.99 | SSIM 0.6208
save display images
Traceback (most recent call last):
  File "/root/PEAN-main/main.py", line 60, in <module>
    main(config, args)
  File "/root/PEAN-main/main.py", line 26, in main
    Mission.train()
  File "/root/PEAN-main/interfaces/super_resolution.py", line 141, in train
    metrics_dict = self.eval(model, val_loader, epoch, parseq)
  File "/root/PEAN-main/interfaces/super_resolution.py", line 354, in eval
    self.tripple_display(images_lr, images_sr[0], images_hr, pred_str_lr_aster, pred_str_sr_aster, label_strs, index)
  File "/root/PEAN-main/interfaces/base.py", line 188, in tripple_display
    tensor_out = image_out[i][:3,:,:]
IndexError: too many indices for tensor of dimension 2

**Comment by xiehuilong** [comment]
需要将image_sr[0]改成image_sr

**Comment by 761qgmpgz943** [comment]
遇到了，用ai改一下吧，这个方向没有必要做下去了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2026年4月21日(周二) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jdfxzzy/PEAN] 在预训练阶段中评估测试集的时候出现以下错误，请问是什么原因？谢谢 (Issue #11)


YongshunWang left a comment (jdfxzzy/PEAN#11)
 
Traceback (most recent call last):
 File "main.py", line 69, in 
 main(config, args)
 File "main.py", line 31, in main
 Mission.train()
 File "/public/home/wangyongshun2025/code/PEANRAS/PEAN-main/interfaces/super_resolution.py", line 144, in train
 metrics_dict = self.eval(model, val_loader, epoch, parseq)
 File "/public/home/wangyongshun2025/code/PEANRAS/PEAN-main/interfaces/super_resolution.py", line 177, in eval
 images_hr, images_lr, label_strs, _ = data
 ValueError: too many values to unpack (expected 4)
 这个问题请问有遇到吗
